param(
    [string]$RepoRoot = (Join-Path $PSScriptRoot ".."),
    [string]$BundleOutput,
    [string]$ExeOutput,
    [switch]$RunPS2EXE,
    [string]$CodeSigningCertificateThumbprint,
    [switch]$SkipCodeSigning
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-WingetterFileSha256 {
    param([string]$Path)

    $hashCommand = Get-Command Get-FileHash -ErrorAction SilentlyContinue
    if ($hashCommand) {
        return (Get-FileHash -LiteralPath $Path -Algorithm SHA256 -ErrorAction Stop).Hash.ToUpperInvariant()
    }

    $resolvedPath = (Resolve-Path -LiteralPath $Path).Path
    $stream = [System.IO.File]::OpenRead($resolvedPath)
    try {
        $sha256 = [System.Security.Cryptography.SHA256]::Create()
        try {
            $hashBytes = $sha256.ComputeHash($stream)
            return ([System.BitConverter]::ToString($hashBytes)).Replace("-", "").ToUpperInvariant()
        } finally {
            if ($sha256 -is [System.IDisposable]) { $sha256.Dispose() }
        }
    } finally {
        $stream.Dispose()
    }
}

function Get-WingetterCodeSigningCertificate {
    param(
        [string]$Thumbprint,
        [bool]$Skip
    )

    if ($Skip) { return $null }
    $certificates = @()
    foreach ($storePath in @("Cert:\CurrentUser\My", "Cert:\LocalMachine\My")) {
        try {
            if (Test-Path $storePath) {
                $certificates += @(Get-ChildItem -Path $storePath -CodeSigningCert -ErrorAction SilentlyContinue)
            }
        } catch {}
    }

    if (![string]::IsNullOrWhiteSpace($Thumbprint)) {
        $normalizedThumbprint = ($Thumbprint -replace '\s', '').ToUpperInvariant()
        return @($certificates | Where-Object { (($_.Thumbprint -replace '\s', '').ToUpperInvariant()) -eq $normalizedThumbprint } | Select-Object -First 1)
    }

    return @($certificates | Where-Object { $_.NotAfter -gt (Get-Date) } | Sort-Object NotAfter -Descending | Select-Object -First 1)
}

$repoRoot = (Resolve-Path $RepoRoot).Path
$launcherPath = Join-Path $repoRoot "Wingetter.ps1"
$sourceDir = Join-Path $repoRoot "src"
if (!(Test-Path $launcherPath)) { throw "Missing launcher at $launcherPath." }
if (!(Test-Path $sourceDir)) { throw "Missing source directory at $sourceDir." }

# The launcher declares the canonical module list inline via
# $Script:WingetterModuleFiles. Reuse it so the bundle order matches whatever
# the latest launcher expects without duplicating the list here.
$launcherText = Get-Content -Path $launcherPath -Raw
$listMatch = [regex]::Match($launcherText, '(?ms)\$Script:WingetterModuleFiles\s*=\s*@\((?<list>.*?)\)')
if (!$listMatch.Success) { throw "Could not locate `$Script:WingetterModuleFiles in $launcherPath." }
$moduleFiles = @(
    ($listMatch.Groups['list'].Value -split ',') |
        ForEach-Object { $_.Trim().Trim('"').Trim("'") } |
        Where-Object { $_ -and $_.EndsWith('.ps1') }
)
if ($moduleFiles.Count -eq 0) { throw "Launcher module list parsed empty." }

if ([string]::IsNullOrWhiteSpace($BundleOutput)) {
    $BundleOutput = Join-Path $repoRoot "release\Wingetter.bundled.ps1"
}
$bundleDir = Split-Path -Parent $BundleOutput
if (![string]::IsNullOrWhiteSpace($bundleDir) -and !(Test-Path $bundleDir)) {
    New-Item -ItemType Directory -Path $bundleDir -Force | Out-Null
}

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("# Wingetter bundled launcher - DO NOT EDIT")
[void]$sb.AppendLine("# Generated by tools\Build-WingetterExe.ps1 from Wingetter.ps1 + src\")
[void]$sb.AppendLine("# Source order: " + ($moduleFiles -join ", "))
[void]$sb.AppendLine("#Requires -Version 5.1")
[void]$sb.AppendLine("`$ErrorActionPreference = 'Stop'")
[void]$sb.AppendLine("")

foreach ($file in $moduleFiles) {
    $modulePath = Join-Path $sourceDir $file
    if (!(Test-Path $modulePath)) { throw "Missing module file $modulePath." }
    [void]$sb.AppendLine("# ===== BEGIN $file =====")
    [void]$sb.AppendLine((Get-Content -Path $modulePath -Raw))
    [void]$sb.AppendLine("# =====  END $file =====")
    [void]$sb.AppendLine("")
}

[void]$sb.AppendLine("Start-Wingetter")
$bundle = $sb.ToString()
Set-Content -Path $BundleOutput -Value $bundle -Encoding UTF8

$tokens = $null
$parseErrors = $null
[System.Management.Automation.Language.Parser]::ParseInput($bundle, [ref]$tokens, [ref]$parseErrors) | Out-Null
if ($parseErrors.Count -gt 0) {
    Write-Host "Bundled script failed to parse:" -ForegroundColor Red
    foreach ($parseError in $parseErrors) {
        Write-Host (" - line {0}: {1}" -f $parseError.Extent.StartLineNumber, $parseError.Message) -ForegroundColor Red
    }
    exit 1
}

Write-Host "Bundle written to $BundleOutput ($($bundle.Length) bytes, $($moduleFiles.Count) modules)."
$bundleHash = Get-WingetterFileSha256 -Path $BundleOutput
Write-Host "Bundle SHA256: $bundleHash"

if (-not $RunPS2EXE) {
    Write-Host "Skipped PS2EXE packaging (pass -RunPS2EXE to build Wingetter.exe)."
    return
}

if ([string]::IsNullOrWhiteSpace($ExeOutput)) {
    $ExeOutput = Join-Path $repoRoot "Wingetter.exe"
}
$iconPath = Join-Path $repoRoot "Wingetter.ico"

if (-not (Get-Module -ListAvailable -Name PS2EXE)) {
    Write-Host "PS2EXE module is not installed. Install it with:" -ForegroundColor Yellow
    Write-Host "  Install-Module PS2EXE -Scope CurrentUser" -ForegroundColor Yellow
    exit 1
}
$ps2exeModule = Get-Module -ListAvailable -Name PS2EXE | Sort-Object Version -Descending | Select-Object -First 1
Import-Module PS2EXE -Force | Out-Null

$ps2exeArgs = @{
    InputFile    = $BundleOutput
    OutputFile   = $ExeOutput
    Title        = "Wingetter"
    Product      = "Wingetter"
    Description  = "Wingetter bundled launcher SHA256 $bundleHash"
    Company      = "SysAdminDoc"
    Copyright    = "MIT"
    Trademark    = "Wingetter"
    Version      = "6.2.0.0"
    NoConsole    = $true
    STA          = $true
    DPIAware     = $true
    SupportOS    = $true
}
if (Test-Path $iconPath) { $ps2exeArgs["IconFile"] = $iconPath }
Invoke-PS2EXE @ps2exeArgs

$certificate = Get-WingetterCodeSigningCertificate -Thumbprint $CodeSigningCertificateThumbprint -Skip ([bool]$SkipCodeSigning)
if ($certificate) {
    $signature = Set-AuthenticodeSignature -FilePath $ExeOutput -Certificate $certificate -TimestampServer "http://timestamp.digicert.com" -ErrorAction Stop
    Write-Host "Wingetter.exe signed with certificate $($certificate.Thumbprint); Authenticode status: $($signature.Status)."
} else {
    Write-Host "No code-signing certificate available; Wingetter.exe remains unsigned and the release manifest must record that state."
}

Write-Host "Wingetter.exe written to $ExeOutput with PS2EXE $($ps2exeModule.Version). Run tools\Test-ReleaseArtifact.ps1 -Update to refresh the manifest."
