# ============================================================================
# PACKAGE GROUPS SYSTEM
# ============================================================================

$Script:GroupsDir = "$env:APPDATA\Wingetter"
$Script:GroupsFile = "$Script:GroupsDir\groups.json"
if (!(Test-Path $Script:GroupsDir)) { New-Item -ItemType Directory -Path $Script:GroupsDir -Force | Out-Null }

function Get-SavedGroups {
    if (Test-Path $Script:GroupsFile) {
        try { return (Get-Content $Script:GroupsFile -Raw | ConvertFrom-Json) }
        catch {
            Move-WingetterCorruptFileAside -Path $Script:GroupsFile
            return [PSCustomObject]@{}
        }
    }
    return [PSCustomObject]@{}
}

function Save-WingetterGroupsFile {
    param([hashtable]$Groups)
    $json = $Groups | ConvertTo-Json -Depth 8
    Set-WingetterFileAtomic -Path $Script:GroupsFile -Content $json -Encoding UTF8
}

function Save-GroupToFile {
    param(
        [string]$Name,
        [string[]]$PackageIds,
        [object[]]$PackageEntries = @()
    )
    $groups = Get-SavedGroups
    $ht = @{}
    foreach ($prop in $groups.PSObject.Properties) { $ht[$prop.Name] = $prop.Value }
    $entries = @(ConvertTo-WingetterGroupPackageEntries -PackageIds $PackageIds -PackageEntries $PackageEntries -AllowCustomInstallOptions)
    $hasInstallOptions = $false
    foreach ($entry in @($entries)) {
        if ($entry.PSObject.Properties["InstallOptions"] -and !(Test-WingetterInstallOptionsEmpty -InstallOptions $entry.InstallOptions)) {
            $hasInstallOptions = $true
            break
        }
    }

    if ($hasInstallOptions) {
        $ht[$Name] = [ordered]@{
            Schema     = "Wingetter.SavedGroup.v1"
            PackageIds = [string[]]@($entries | ForEach-Object { [string]$_.PackageIdentifier })
            Packages   = [object[]]$entries
        }
    } else {
        $ht[$Name] = [string[]]@($entries | ForEach-Object { [string]$_.PackageIdentifier })
    }
    Save-WingetterGroupsFile -Groups $ht
}

function Remove-GroupFromFile {
    param([string]$Name)
    $groups = Get-SavedGroups
    $ht = @{}
    foreach ($prop in $groups.PSObject.Properties) { if ($prop.Name -ne $Name) { $ht[$prop.Name] = $prop.Value } }
    Save-WingetterGroupsFile -Groups $ht
}

function ConvertTo-WingetterPowerShellSingleQuotedString {
    param([string]$Value)
    "'" + (([string]$Value) -replace "'", "''") + "'"
}

function Export-GroupAsPS1 {
    param(
        [string]$GroupName,
        [string[]]$PackageIds,
        [string]$FilePath,
        [bool]$Silent = $true,
        [bool]$AcceptAgreements = $true,
        [object[]]$PackageEntries = @()
    )
    $entries = @(ConvertTo-WingetterGroupPackageEntries -PackageIds $PackageIds -PackageEntries $PackageEntries -AllowCustomInstallOptions)
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine("<#")
    [void]$sb.AppendLine(".SYNOPSIS")
    [void]$sb.AppendLine("    WinGet Package Group Installer - $GroupName")
    [void]$sb.AppendLine(".DESCRIPTION")
    [void]$sb.AppendLine("    Auto-generated by Wingetter")
    [void]$sb.AppendLine("    Installs $($entries.Count) packages via winget")
    [void]$sb.AppendLine("    Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
    [void]$sb.AppendLine("#>")
    [void]$sb.AppendLine("")
    $safeGroupName = ConvertTo-WingetterPowerShellSingleQuotedString -Value $GroupName
    [void]$sb.AppendLine('Write-Host "====================================" -ForegroundColor Cyan')
    [void]$sb.AppendLine("Write-Host (' WinGet Package Group: ' + $safeGroupName) -ForegroundColor Cyan")
    [void]$sb.AppendLine("Write-Host `" $($entries.Count) packages to install`" -ForegroundColor Cyan")
    [void]$sb.AppendLine('Write-Host "====================================" -ForegroundColor Cyan')
    [void]$sb.AppendLine('Write-Host ""')
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine('# Check for winget')
    [void]$sb.AppendLine('if (!(Get-Command winget -ErrorAction SilentlyContinue)) {')
    [void]$sb.AppendLine('    Write-Host "ERROR: winget not found. Install it from the Microsoft Store." -ForegroundColor Red')
    [void]$sb.AppendLine('    exit 1')
    [void]$sb.AppendLine('}')
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine('$total = ' + $entries.Count)
    [void]$sb.AppendLine('$current = 0; $ok = 0; $fail = 0; $skip = 0')
    [void]$sb.AppendLine('$useSilent = ' + $(if ($Silent) { '$true' } else { '$false' }))
    [void]$sb.AppendLine('$acceptAgreements = ' + $(if ($AcceptAgreements) { '$true' } else { '$false' }))
    [void]$sb.AppendLine("")

    [void]$sb.AppendLine('$packages = @(')
    foreach ($entry in @($entries)) {
        [void]$sb.AppendLine("    [pscustomobject]@{")
        [void]$sb.AppendLine("        Id = $(ConvertTo-WingetterPowerShellSingleQuotedString -Value ([string]$entry.PackageIdentifier))")
        $sourceName = if ($entry.PSObject.Properties["SourceName"]) { [string]$entry.SourceName } else { "" }
        [void]$sb.AppendLine("        SourceName = $(ConvertTo-WingetterPowerShellSingleQuotedString -Value $sourceName)")
        [void]$sb.AppendLine("        InstallOptions = @{")
        if ($entry.PSObject.Properties["InstallOptions"]) {
            foreach ($propertyName in @("Version", "Scope", "Architecture", "InstallerType", "Locale", "Location", "Custom")) {
                $property = $entry.InstallOptions.PSObject.Properties[$propertyName]
                if ($property -and ![string]::IsNullOrWhiteSpace([string]$property.Value)) {
                    [void]$sb.AppendLine("            $propertyName = $(ConvertTo-WingetterPowerShellSingleQuotedString -Value ([string]$property.Value))")
                }
            }
        }
        [void]$sb.AppendLine("        }")
        [void]$sb.AppendLine("    }")
    }
    [void]$sb.AppendLine(')')
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine('foreach ($pkg in $packages) {')
    [void]$sb.AppendLine('    $current++')
    [void]$sb.AppendLine('    $pct = [math]::Round(($current / $total) * 100)')
    [void]$sb.AppendLine('    Write-Host "[$current/$total] ($pct%) Installing $($pkg.Id)..." -ForegroundColor Yellow')
    [void]$sb.AppendLine("    `$wingetArgs = @('install', '--id', [string]`$pkg.Id, '--exact', '--verbose-logs', '--disable-interactivity')")
    [void]$sb.AppendLine("    if (![string]::IsNullOrWhiteSpace([string]`$pkg.SourceName)) { `$wingetArgs += @('--source', [string]`$pkg.SourceName) }")
    [void]$sb.AppendLine("    if (`$pkg.InstallOptions.ContainsKey('Version')) { `$wingetArgs += @('--version', [string]`$pkg.InstallOptions['Version']) }")
    [void]$sb.AppendLine("    if (`$pkg.InstallOptions.ContainsKey('Scope')) { `$wingetArgs += @('--scope', [string]`$pkg.InstallOptions['Scope']) }")
    [void]$sb.AppendLine("    if (`$pkg.InstallOptions.ContainsKey('Architecture')) { `$wingetArgs += @('--architecture', [string]`$pkg.InstallOptions['Architecture']) }")
    [void]$sb.AppendLine("    if (`$pkg.InstallOptions.ContainsKey('InstallerType')) { `$wingetArgs += @('--installer-type', [string]`$pkg.InstallOptions['InstallerType']) }")
    [void]$sb.AppendLine("    if (`$pkg.InstallOptions.ContainsKey('Locale')) { `$wingetArgs += @('--locale', [string]`$pkg.InstallOptions['Locale']) }")
    [void]$sb.AppendLine("    if (`$pkg.InstallOptions.ContainsKey('Location')) { `$wingetArgs += @('--location', [string]`$pkg.InstallOptions['Location']) }")
    [void]$sb.AppendLine("    if (`$pkg.InstallOptions.ContainsKey('Custom')) { `$wingetArgs += @('--custom', [string]`$pkg.InstallOptions['Custom']) }")
    [void]$sb.AppendLine("    if (`$useSilent) { `$wingetArgs += '--silent' }")
    [void]$sb.AppendLine("    if (`$acceptAgreements) { `$wingetArgs += @('--accept-package-agreements', '--accept-source-agreements') }")
    [void]$sb.AppendLine("    `$result = & winget @wingetArgs 2>&1 | Out-String")
    [void]$sb.AppendLine('    if ($LASTEXITCODE -eq 0) {')
    [void]$sb.AppendLine('        Write-Host "  OK" -ForegroundColor Green; $ok++')
    [void]$sb.AppendLine('    } elseif ($result -match "already installed|No available upgrade") {')
    [void]$sb.AppendLine('        Write-Host "  Already installed" -ForegroundColor DarkGray; $skip++')
    [void]$sb.AppendLine('    } else {')
    [void]$sb.AppendLine('        Write-Host "  FAILED" -ForegroundColor Red; $fail++')
    [void]$sb.AppendLine('    }')
    [void]$sb.AppendLine('}')
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine('Write-Host ""')
    [void]$sb.AppendLine('Write-Host "====================================" -ForegroundColor Cyan')
    [void]$sb.AppendLine('Write-Host " Results: $ok installed, $skip already present, $fail failed" -ForegroundColor Cyan')
    [void]$sb.AppendLine('Write-Host "====================================" -ForegroundColor Cyan')
    [void]$sb.AppendLine('Read-Host "Press Enter to exit"')

    Set-WingetterFileAtomic -Path $FilePath -Content $sb.ToString() -Encoding UTF8
}

function Export-GroupAsJSON {
    param(
        [string]$GroupName,
        [string[]]$PackageIds,
        [string]$FilePath,
        [object[]]$PackageEntries = @()
    )
    $entries = @(ConvertTo-WingetterGroupPackageEntries -PackageIds $PackageIds -PackageEntries $PackageEntries -AllowCustomInstallOptions)
    $ids = [string[]]@($entries | ForEach-Object { [string]$_.PackageIdentifier })
    $obj = @{
        Schema     = "Wingetter.Group.v1"
        GroupName  = $GroupName
        Generated  = (Get-Date -Format "yyyy-MM-dd HH:mm:ss")
        Generator  = "Wingetter"
        AppCount   = $ids.Count
        PackageIds = $ids
        Packages   = [object[]]$entries
    }
    Set-WingetterFileAtomic -Path $FilePath -Content ($obj | ConvertTo-Json -Depth 8) -Encoding UTF8
}

function Export-GroupAsWinGetJSON {
    param(
        [string]$GroupName,
        [string[]]$PackageIds,
        [string]$FilePath,
        [object[]]$PackageEntries = @()
    )

    # GroupName is accepted for caller symmetry with Export-Group; the official
    # WinGet import/export schema has no top-level group field, so the value is
    # intentionally not embedded in the exported JSON.
    [void]$GroupName
    $wingetVersion = try { (winget --version 2>$null) } catch { $null }
    $entries = @(ConvertTo-WingetterGroupPackageEntries -PackageIds $PackageIds -PackageEntries $PackageEntries -AllowCustomInstallOptions)
    $packages = @($entries | ForEach-Object {
        $package = [ordered]@{ PackageIdentifier = [string]$_.PackageIdentifier }
        if ($_.PSObject.Properties["InstallOptions"] -and $_.InstallOptions.PSObject.Properties["Version"]) {
            $package["Version"] = [string]$_.InstallOptions.Version
        }
        $package
    })

    $obj = [ordered]@{
        '$schema'     = "https://aka.ms/winget-packages.schema.2.0.json"
        CreationDate  = (Get-Date).ToUniversalTime().ToString("o")
        Sources       = @(
            [ordered]@{
                Packages      = $packages
                SourceDetails = [ordered]@{
                    Argument   = "https://cdn.winget.microsoft.com/cache"
                    Identifier = "Microsoft.Winget.Source_8wekyb3d8bbwe"
                    Name       = "winget"
                    Type       = "Microsoft.PreIndexed.Package"
                }
            }
        )
    }
    if ($wingetVersion) { $obj["WinGetVersion"] = [string]$wingetVersion }

    Set-WingetterFileAtomic -Path $FilePath -Content ($obj | ConvertTo-Json -Depth 8) -Encoding UTF8
}

function Get-JsonPropertyValue {
    param([object]$InputObject, [string]$PropertyName)
    if ($null -eq $InputObject) { return $null }
    $property = $InputObject.PSObject.Properties[$PropertyName]
    if ($property) { return $property.Value }
    return $null
}

function Test-JsonPropertyPresence {
    param([object]$InputObject, [string]$PropertyName)
    if ($null -eq $InputObject) { return $false }
    return [bool]$InputObject.PSObject.Properties[$PropertyName]
}

$Script:WingetterImportMaxPackages = 5000

function Get-WingetterPackageEntryId {
    param([object]$Package)

    foreach ($propertyName in @("PackageIdentifier", "WingetId", "PackageId", "Id")) {
        $value = Get-WingetterObjectPropertyValue -InputObject $Package -PropertyName $propertyName
        if (![string]::IsNullOrWhiteSpace([string]$value)) { return [string]$value }
    }
    return ""
}

function Get-WingetterPackageEntryInstallOptions {
    param(
        [object]$Package,
        [switch]$AllowCustomInstallOptions,
        [string[]]$AllowedInstallOptionFields = @()
    )

    $installOptions = Get-WingetterObjectPropertyValue -InputObject $Package -PropertyName "InstallOptions"
    if ($null -eq $installOptions) {
        $inlineOptions = [ordered]@{}
        foreach ($propertyName in @("Version", "PackageVersion", "Scope", "Architecture", "InstallerType", "Installer", "Locale", "Location", "InstallLocation", "Custom")) {
            $propertyValue = Get-WingetterObjectPropertyValue -InputObject $Package -PropertyName $propertyName
            if ($null -ne $propertyValue -and ![string]::IsNullOrWhiteSpace([string]$propertyValue)) {
                $inlineOptions[$propertyName] = $propertyValue
            }
        }
        if ($inlineOptions.Count -gt 0) { $installOptions = [PSCustomObject]$inlineOptions }
    }

    ConvertTo-WingetterInstallOptions -InstallOptions $installOptions -AllowedProperties $AllowedInstallOptionFields -AllowCustom ([bool]$AllowCustomInstallOptions)
}

function New-WingetterGroupPackageEntry {
    param(
        [string]$PackageId,
        [string]$SourceName = "",
        [string]$Name = "",
        [object]$InstallOptions = $null,
        [switch]$AllowCustomInstallOptions,
        [string[]]$AllowedInstallOptionFields = @()
    )

    if ([string]::IsNullOrWhiteSpace($PackageId)) { throw "Package entry is missing PackageIdentifier." }
    $entry = [ordered]@{
        PackageIdentifier = $PackageId
    }
    if (![string]::IsNullOrWhiteSpace($SourceName)) { $entry["SourceName"] = $SourceName }
    if (![string]::IsNullOrWhiteSpace($Name)) { $entry["Name"] = $Name }

    $options = ConvertTo-WingetterInstallOptions -InstallOptions $InstallOptions -AllowedProperties $AllowedInstallOptionFields -AllowCustom ([bool]$AllowCustomInstallOptions)
    if (!(Test-WingetterInstallOptionsEmpty -InstallOptions $options)) {
        $entry["InstallOptions"] = $options
    }
    return [PSCustomObject]$entry
}

function ConvertTo-WingetterGroupPackageEntries {
    param(
        [string[]]$PackageIds = @(),
        [object[]]$PackageEntries = @(),
        [switch]$AllowCustomInstallOptions,
        [string[]]$AllowedInstallOptionFields = @()
    )

    $entries = [System.Collections.ArrayList]::new()
    if ($PackageEntries -and @($PackageEntries).Count -gt 0) {
        foreach ($package in @($PackageEntries)) {
            if ($package -is [string]) {
                if (![string]::IsNullOrWhiteSpace([string]$package)) {
                    [void]$entries.Add((New-WingetterGroupPackageEntry -PackageId ([string]$package) -AllowCustomInstallOptions:$AllowCustomInstallOptions -AllowedInstallOptionFields $AllowedInstallOptionFields))
                }
                continue
            }

            $packageId = Get-WingetterPackageEntryId -Package $package
            if ([string]::IsNullOrWhiteSpace($packageId)) { continue }
            $sourceName = [string](Get-WingetterObjectPropertyValue -InputObject $package -PropertyName "SourceName")
            if ([string]::IsNullOrWhiteSpace($sourceName)) { $sourceName = [string](Get-WingetterObjectPropertyValue -InputObject $package -PropertyName "Source") }
            $name = [string](Get-WingetterObjectPropertyValue -InputObject $package -PropertyName "Name")
            $options = Get-WingetterPackageEntryInstallOptions -Package $package -AllowCustomInstallOptions:$AllowCustomInstallOptions -AllowedInstallOptionFields $AllowedInstallOptionFields
            [void]$entries.Add((New-WingetterGroupPackageEntry -PackageId $packageId -SourceName $sourceName -Name $name -InstallOptions $options -AllowCustomInstallOptions:$AllowCustomInstallOptions -AllowedInstallOptionFields $AllowedInstallOptionFields))
        }
    } else {
        foreach ($id in @($PackageIds)) {
            if (![string]::IsNullOrWhiteSpace([string]$id)) {
                [void]$entries.Add((New-WingetterGroupPackageEntry -PackageId ([string]$id) -AllowCustomInstallOptions:$AllowCustomInstallOptions -AllowedInstallOptionFields $AllowedInstallOptionFields))
            }
        }
    }

    return [object[]]$entries.ToArray()
}

function Get-WingetterGroupRecordPackageEntries {
    param([object]$GroupRecord)

    if ($null -eq $GroupRecord) { return @() }
    if ($GroupRecord -is [string]) {
        return [object[]]@(New-WingetterGroupPackageEntry -PackageId ([string]$GroupRecord))
    }

    $packages = Get-WingetterObjectPropertyValue -InputObject $GroupRecord -PropertyName "Packages"
    if ($packages) {
        return ConvertTo-WingetterGroupPackageEntries -PackageEntries @($packages) -AllowCustomInstallOptions
    }

    $packageIds = Get-WingetterObjectPropertyValue -InputObject $GroupRecord -PropertyName "PackageIds"
    if ($packageIds) {
        return ConvertTo-WingetterGroupPackageEntries -PackageIds ([string[]]@($packageIds | ForEach-Object { [string]$_ }))
    }

    return ConvertTo-WingetterGroupPackageEntries -PackageIds ([string[]]@($GroupRecord | ForEach-Object { [string]$_ }))
}

function Get-WingetterGroupRecordPackageIds {
    param([object]$GroupRecord)

    [string[]]@(Get-WingetterGroupRecordPackageEntries -GroupRecord $GroupRecord | ForEach-Object { [string]$_.PackageIdentifier })
}

function Import-PackageIdsFromJSON {
    param([object]$Content, [string]$FallbackGroupName = "Imported Group")

    $entries = [System.Collections.ArrayList]::new()
    $sourceNames = [System.Collections.ArrayList]::new()
    $warnings = [System.Collections.ArrayList]::new()
    $groupName = $FallbackGroupName
    $format = "Unknown"

    $packageIds = Get-JsonPropertyValue -InputObject $Content -PropertyName "PackageIds"
    $wingetSources = Get-JsonPropertyValue -InputObject $Content -PropertyName "Sources"
    $flatPackages = Get-JsonPropertyValue -InputObject $Content -PropertyName "Packages"
    # Classify by property *presence* rather than truthiness so that an explicitly
    # empty Sources/Packages array is still recognized as the corresponding WinGet
    # schema (zero packages, zero warnings) rather than dropping into the
    # unrecognized-format throw.
    $hasPackageIds = Test-JsonPropertyPresence -InputObject $Content -PropertyName "PackageIds"
    $hasWingetSources = Test-JsonPropertyPresence -InputObject $Content -PropertyName "Sources"
    $hasFlatPackages = Test-JsonPropertyPresence -InputObject $Content -PropertyName "Packages"

    if ($hasPackageIds) {
        $format = "Wingetter group JSON"
        $name = Get-JsonPropertyValue -InputObject $Content -PropertyName "GroupName"
        if ($name) { $groupName = [string]$name }
        $wingetterPackages = Get-JsonPropertyValue -InputObject $Content -PropertyName "Packages"
        if ($wingetterPackages) {
            foreach ($entry in ConvertTo-WingetterGroupPackageEntries -PackageEntries @($wingetterPackages) -AllowCustomInstallOptions) {
                [void]$entries.Add($entry)
            }
        } else {
            foreach ($id in @($packageIds)) {
                if (![string]::IsNullOrWhiteSpace([string]$id)) {
                    [void]$entries.Add((New-WingetterGroupPackageEntry -PackageId ([string]$id)))
                }
            }
        }
    } elseif ($hasWingetSources) {
        $format = "WinGet import JSON"
        foreach ($source in @($wingetSources)) {
            $sourceDetails = Get-JsonPropertyValue -InputObject $source -PropertyName "SourceDetails"
            $sourceName = Get-JsonPropertyValue -InputObject $sourceDetails -PropertyName "Name"
            if (!$sourceName) { $sourceName = Get-JsonPropertyValue -InputObject $source -PropertyName "Name" }
            if ($sourceName) {
                [void]$sourceNames.Add([string]$sourceName)
            } else {
                [void]$warnings.Add("A WinGet source entry is missing SourceDetails.Name.")
            }

            $sourcePackages = Get-JsonPropertyValue -InputObject $source -PropertyName "Packages"
            foreach ($package in @($sourcePackages)) {
                $id = Get-JsonPropertyValue -InputObject $package -PropertyName "PackageIdentifier"
                if ($id) {
                    $options = Get-WingetterPackageEntryInstallOptions -Package $package
                    if (!(Test-WingetterInstallOptionsEmpty -InstallOptions $options)) {
                        [void]$warnings.Add("Preserved safe install options for '$id' from WinGet import metadata; review before running.")
                    }
                    [void]$entries.Add((New-WingetterGroupPackageEntry -PackageId ([string]$id) -SourceName ([string]$sourceName) -InstallOptions $options))
                } else {
                    [void]$warnings.Add("A WinGet package entry is missing PackageIdentifier.")
                }
            }
        }
    } elseif ($hasFlatPackages) {
        $format = "WinGet package list JSON"
        foreach ($package in @($flatPackages)) {
            $id = Get-JsonPropertyValue -InputObject $package -PropertyName "PackageIdentifier"
            if ($id) {
                $options = Get-WingetterPackageEntryInstallOptions -Package $package
                if (!(Test-WingetterInstallOptionsEmpty -InstallOptions $options)) {
                    [void]$warnings.Add("Preserved safe install options for '$id' from package-list metadata; review before running.")
                }
                [void]$entries.Add((New-WingetterGroupPackageEntry -PackageId ([string]$id) -InstallOptions $options))
            }
        }
    } elseif ($Content -is [System.Array]) {
        $format = "Package ID array JSON"
        foreach ($id in @($Content)) {
            if (![string]::IsNullOrWhiteSpace([string]$id)) {
                [void]$entries.Add((New-WingetterGroupPackageEntry -PackageId ([string]$id)))
            }
        }
    } else {
        throw "Unrecognized JSON format"
    }

    $seen = @{}
    $uniqueIds = [System.Collections.ArrayList]::new()
    $uniqueEntries = [System.Collections.ArrayList]::new()
    foreach ($entry in $entries) {
        $id = [string]$entry.PackageIdentifier
        if (!$seen.ContainsKey($id)) {
            $seen[$id] = $true
            [void]$uniqueIds.Add($id)
            [void]$uniqueEntries.Add($entry)
        }
    }

    # Reject obviously oversized imports rather than spending memory parsing
    # them. The actual install loop is serial and would never finish on tens
    # of thousands of packages anyway; better to fail loud here.
    if ($uniqueIds.Count -gt $Script:WingetterImportMaxPackages) {
        throw "Imported profile contains $($uniqueIds.Count) packages, which exceeds the $($Script:WingetterImportMaxPackages)-package limit."
    }

    [PSCustomObject]@{
        GroupName   = $groupName
        Format      = $format
        PackageIds  = [string[]]$uniqueIds.ToArray([string])
        PackageEntries = [object[]]$uniqueEntries.ToArray()
        SourceNames = [string[]]$sourceNames.ToArray([string])
        Warnings    = [string[]]$warnings.ToArray([string])
    }
}

function New-WingetterMigrationReport {
    param(
        [string]$ProfileName,
        [object[]]$SelectedPackages,
        [object[]]$RunResults,
        [hashtable]$InstalledRecords = @{},
        [string[]]$ImportWarnings = @(),
        [string]$RunLogDir = "",
        [object]$RunPlan = $null
    )

    $generatedUtc = (Get-Date).ToUniversalTime().ToString("o")
    $statusCounts = @{}
    foreach ($statusName in @("SUCCESS", "UP TO DATE", "FAILED", "CANCELLED")) {
        $statusCounts[$statusName] = 0
    }

    $resultsById = @{}
    foreach ($result in @($RunResults)) {
        if ($result.PackageId) { $resultsById[[string]$result.PackageId] = $result }
        $status = [string]$result.Status
        if (!$statusCounts.ContainsKey($status)) { $statusCounts[$status] = 0 }
        $statusCounts[$status]++
    }

    $packages = New-Object System.Collections.ArrayList
    foreach ($package in @($SelectedPackages)) {
        $id = if ($package.WingetId) { [string]$package.WingetId } elseif ($package.PackageId) { [string]$package.PackageId } else { [string]$package }
        $name = if ($package.Name) { [string]$package.Name } else { $id }
        $result = if ($resultsById.ContainsKey($id)) { $resultsById[$id] } else { $null }
        $installed = if ($InstalledRecords -and $InstalledRecords.ContainsKey($id)) { $InstalledRecords[$id] } else { $null }

        [void]$packages.Add([ordered]@{
            name             = $name
            packageId        = $id
            status           = if ($result) { [string]$result.Status } else { "NOT RUN" }
            action           = if ($result) { [string]$result.Action } else { "" }
            exitCode         = if ($result) { $result.ExitCode } else { $null }
            command          = if ($result) { [string]$result.Command } else { "" }
            installedVersion = if ($installed) { [string]$installed.InstalledVersion } else { "" }
            availableVersion = if ($installed) { [string]$installed.AvailableVersion } else { "" }
            source           = if ($installed) { [string]$installed.Source } else { "" }
            scope            = if ($installed) { [string]$installed.Scope } else { "" }
            detectionMethod  = if ($installed) { [string]$installed.DetectionMethod } else { "" }
            scannedAtUtc     = if ($installed) { [string]$installed.ScannedAtUtc } else { "" }
            resultPath       = if ($result) { [string]$result.ResultPath } else { "" }
            stdoutExcerpt    = if ($result) { [string]$result.StdOutExcerpt } else { "" }
            stderrExcerpt    = if ($result) { [string]$result.StdErrExcerpt } else { "" }
        })
    }

    [ordered]@{
        schema         = "Wingetter.MigrationReport.v1"
        generatedUtc   = $generatedUtc
        profileName    = $ProfileName
        runLogDir      = $RunLogDir
        importWarnings = @($ImportWarnings)
        runPlan        = $RunPlan
        summary        = [ordered]@{
            selected  = @($SelectedPackages).Count
            succeeded = [int]$statusCounts["SUCCESS"]
            skipped   = [int]$statusCounts["UP TO DATE"]
            failed    = [int]$statusCounts["FAILED"]
            cancelled = [int]$statusCounts["CANCELLED"]
        }
        packages       = @($packages)
    }
}

function ConvertTo-WingetterMigrationMarkdown {
    param([object]$Report)

    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine("# Wingetter Migration Report")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("- Generated UTC: $($Report.generatedUtc)")
    [void]$sb.AppendLine("- Profile: $($Report.profileName)")
    [void]$sb.AppendLine("- Run log directory: $($Report.runLogDir)")
    if ($Report.runPlan) {
        [void]$sb.AppendLine("- Preflight plan: $($Report.runPlan.Summary.runnable) runnable, $($Report.runPlan.Summary.skipped) skipped, $($Report.runPlan.Summary.blocked) blocked")
    }
    [void]$sb.AppendLine("- Selected: $($Report.summary.selected)")
    [void]$sb.AppendLine("- Succeeded: $($Report.summary.succeeded)")
    [void]$sb.AppendLine("- Skipped/current: $($Report.summary.skipped)")
    [void]$sb.AppendLine("- Failed: $($Report.summary.failed)")
    [void]$sb.AppendLine("- Cancelled: $($Report.summary.cancelled)")
    if (@($Report.importWarnings).Count -gt 0) {
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("## Import Warnings")
        foreach ($warning in @($Report.importWarnings)) { [void]$sb.AppendLine("- $warning") }
    }
    if ($Report.runPlan) {
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("## Preflight Plan")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("| Package | ID | Plan | Status | Reason |")
        [void]$sb.AppendLine("|---|---|---|---|---|")
        foreach ($package in @($Report.runPlan.Packages)) {
            $pName = ([string]$package.Name) -replace '\|', '\|'
            $pkgId = ([string]$package.PackageId) -replace '\|', '\|'
            $pAction = ([string]$package.PlannedAction) -replace '\|', '\|'
            $pStatus = ([string]$package.Status) -replace '\|', '\|'
            $reason = ([string]$package.Reason) -replace '\|', '\|'
            [void]$sb.AppendLine("| $pName | $pkgId | $pAction | $pStatus | $reason |")
        }
    }
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("## Packages")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("| Package | ID | Status | Installed | Available | Source | Command |")
    [void]$sb.AppendLine("|---|---|---|---|---|---|---|")
    foreach ($package in @($Report.packages)) {
        $rName = ([string]$package.name) -replace '\|', '\|'
        $rId = ([string]$package.packageId) -replace '\|', '\|'
        $rStatus = ([string]$package.status) -replace '\|', '\|'
        $rInstalled = ([string]$package.installedVersion) -replace '\|', '\|'
        $rAvailable = ([string]$package.availableVersion) -replace '\|', '\|'
        $rSource = ([string]$package.source) -replace '\|', '\|'
        $command = ([string]$package.command) -replace '\|', '\|'
        [void]$sb.AppendLine("| $rName | $rId | $rStatus | $rInstalled | $rAvailable | $rSource | ``$command`` |")
    }
    return $sb.ToString()
}

function Export-WingetterMigrationReport {
    param(
        [object]$Report,
        [string]$FilePath
    )

    $extension = [System.IO.Path]::GetExtension($FilePath)
    if ($extension -eq ".md") {
        Set-WingetterFileAtomic -Path $FilePath -Content (ConvertTo-WingetterMigrationMarkdown -Report $Report) -Encoding UTF8
    } else {
        Set-WingetterFileAtomic -Path $FilePath -Content ($Report | ConvertTo-Json -Depth 8) -Encoding UTF8
    }
}

function Get-WingetterRetryPackagesFromReport {
    param([object]$Report)

    if ($null -eq $Report -or $null -eq $Report.packages) { return @() }
    $retryStatuses = @("FAILED", "CANCELLED", "NOT RUN")
    $retryable = [System.Collections.ArrayList]::new()
    foreach ($pkg in @($Report.packages)) {
        $status = [string]$pkg.status
        if ($retryStatuses -contains $status) {
            $installOptions = $null
            if ($Report.runPlan -and $Report.runPlan.Packages) {
                foreach ($planPkg in @($Report.runPlan.Packages)) {
                    if ([string]$planPkg.PackageId -eq [string]$pkg.packageId -and $planPkg.PSObject.Properties["InstallOptions"]) {
                        $installOptions = $planPkg.InstallOptions
                        break
                    }
                }
            }
            [void]$retryable.Add([PSCustomObject]@{
                Name           = [string]$pkg.name
                WingetId       = [string]$pkg.packageId
                SourceName     = if ($pkg.source) { [string]$pkg.source } else { "winget" }
                PriorStatus    = $status
                InstallOptions = $installOptions
            })
        }
    }
    return [object[]]$retryable.ToArray()
}

function New-WingetterComplianceReport {
    param(
        [string]$ProfileName,
        [object[]]$DesiredPackages,
        [hashtable]$InstalledRecords = @{},
        [hashtable]$PinStatusesById = @{},
        [object]$SourcePolicy = $null
    )

    $results = [System.Collections.ArrayList]::new()
    $stateCount = @{ Missing = 0; Current = 0; UpdateAvailable = 0; Pinned = 0; SourceBlocked = 0; Unresolved = 0 }

    foreach ($pkg in @($DesiredPackages)) {
        $id = if ($pkg -is [string]) { $pkg }
              elseif ($pkg.PSObject.Properties["WingetId"]) { [string]$pkg.WingetId }
              elseif ($pkg.PSObject.Properties["PackageIdentifier"]) { [string]$pkg.PackageIdentifier }
              else { [string]$pkg }
        $name = if ($pkg.PSObject.Properties["Name"]) { [string]$pkg.Name } else { $id }

        $installed = if ($InstalledRecords.ContainsKey($id)) { $InstalledRecords[$id] } else { $null }
        $pin = if ($PinStatusesById.ContainsKey($id)) { $PinStatusesById[$id] } else { $null }
        $isPinned = ($null -ne $pin -and $pin.PSObject.Properties["IsPinned"] -and [bool]$pin.IsPinned)

        $sourceBlocked = $false
        if ($null -ne $SourcePolicy -and [bool]$SourcePolicy.CorporateMode -and [bool]$SourcePolicy.RequireAllowedSource) {
            $sourceName = if ($null -ne $installed) { [string]$installed.Source } elseif ($pkg.PSObject.Properties["SourceName"]) { [string]$pkg.SourceName } else { "winget" }
            $allowedNames = @($SourcePolicy.AllowedSources | ForEach-Object { [string]$_.Name })
            if ($allowedNames.Count -gt 0 -and $allowedNames -notcontains $sourceName) { $sourceBlocked = $true }
        }

        $state = "Unresolved"
        if ($sourceBlocked) {
            $state = "SourceBlocked"
        } elseif ($null -eq $installed) {
            $state = "Missing"
        } elseif ($installed.PSObject.Properties["IsUpdateAvailable"] -and [bool]$installed.IsUpdateAvailable) {
            $state = if ($isPinned) { "Pinned" } else { "UpdateAvailable" }
        } else {
            $state = "Current"
        }

        $stateCount[$state]++
        [void]$results.Add([PSCustomObject][ordered]@{
            PackageId        = $id
            Name             = $name
            State            = $state
            InstalledVersion = if ($installed) { [string]$installed.InstalledVersion } else { "" }
            AvailableVersion = if ($installed) { [string]$installed.AvailableVersion } else { "" }
            Source           = if ($installed) { [string]$installed.Source } else { "" }
            PinType          = if ($isPinned) { [string]$pin.PinType } else { "" }
            SourceBlocked    = [bool]$sourceBlocked
        })
    }

    [PSCustomObject][ordered]@{
        Schema       = "Wingetter.ComplianceReport.v1"
        GeneratedUtc = (Get-Date).ToUniversalTime().ToString("o")
        ProfileName  = $ProfileName
        TotalDesired = @($DesiredPackages).Count
        Summary      = [PSCustomObject][ordered]@{
            Current         = [int]$stateCount["Current"]
            Missing         = [int]$stateCount["Missing"]
            UpdateAvailable = [int]$stateCount["UpdateAvailable"]
            Pinned          = [int]$stateCount["Pinned"]
            SourceBlocked   = [int]$stateCount["SourceBlocked"]
            Unresolved      = [int]$stateCount["Unresolved"]
        }
        Packages     = [object[]]$results.ToArray()
    }
}

function Export-WingetterRunLockfile {
    param(
        [object]$Report,
        [string]$FilePath
    )

    if ($null -eq $Report -or $null -eq $Report.packages) { return $null }
    $entries = [System.Collections.ArrayList]::new()
    foreach ($pkg in @($Report.packages)) {
        $status = [string]$pkg.status
        if ($status -ne "SUCCESS" -and $status -ne "UP TO DATE") { continue }

        $installerUrl = ""
        $installerHash = ""
        if (![string]::IsNullOrWhiteSpace([string]$pkg.resultPath) -and (Test-Path -LiteralPath ([string]$pkg.resultPath))) {
            try {
                $resultData = Get-Content -LiteralPath ([string]$pkg.resultPath) -Raw | ConvertFrom-Json
                if ($resultData.PSObject.Properties["Command"]) {
                    $cmd = [string]$resultData.Command
                    if ($cmd -match '--version\s+"?([^\s"]+)') { }
                }
            } catch {}
        }

        $installOptions = $null
        if ($Report.runPlan -and $Report.runPlan.Packages) {
            foreach ($planPkg in @($Report.runPlan.Packages)) {
                if ([string]$planPkg.PackageId -eq [string]$pkg.packageId -and $planPkg.PSObject.Properties["InstallOptions"]) {
                    $installOptions = $planPkg.InstallOptions
                    break
                }
            }
        }

        [void]$entries.Add([PSCustomObject][ordered]@{
            PackageId        = [string]$pkg.packageId
            Name             = [string]$pkg.name
            Source           = if ($pkg.source) { [string]$pkg.source } else { "winget" }
            InstalledVersion = [string]$pkg.installedVersion
            AvailableVersion = [string]$pkg.availableVersion
            Status           = $status
            InstallOptions   = $installOptions
        })
    }

    $lockfile = [PSCustomObject][ordered]@{
        Schema       = "Wingetter.Lockfile.v1"
        GeneratedUtc = (Get-Date).ToUniversalTime().ToString("o")
        ProfileName  = if ($Report.profileName) { [string]$Report.profileName } else { "" }
        PackageCount = $entries.Count
        Packages     = [object[]]$entries.ToArray()
    }

    if (![string]::IsNullOrWhiteSpace($FilePath)) {
        Set-WingetterFileAtomic -Path $FilePath -Content ($lockfile | ConvertTo-Json -Depth 8) -Encoding UTF8
    }
    return $lockfile
}

function Compare-WingetterLockfile {
    param(
        [object]$Lockfile,
        [hashtable]$InstalledRecords = @{}
    )

    if ($null -eq $Lockfile -or $null -eq $Lockfile.Packages) { return @() }
    $drifts = [System.Collections.ArrayList]::new()
    foreach ($entry in @($Lockfile.Packages)) {
        $id = [string]$entry.PackageId
        $installed = if ($InstalledRecords.ContainsKey($id)) { $InstalledRecords[$id] } else { $null }
        $drift = "None"
        if ($null -eq $installed) {
            $drift = "Missing"
        } elseif ([string]$installed.InstalledVersion -ne [string]$entry.InstalledVersion) {
            $drift = "VersionChanged"
        }
        [void]$drifts.Add([PSCustomObject][ordered]@{
            PackageId       = $id
            Name            = [string]$entry.Name
            LockedVersion   = [string]$entry.InstalledVersion
            CurrentVersion  = if ($installed) { [string]$installed.InstalledVersion } else { "" }
            Drift           = $drift
        })
    }
    return [object[]]$drifts.ToArray()
}

# Pre-built groups
$Script:BuiltInGroups = [ordered]@{
    "Essential PC Setup" = @(
        "Google.Chrome","Mozilla.Firefox","7zip.7zip","VideoLAN.VLC","Notepad++.Notepad++",
        "voidtools.Everything","Adobe.Acrobat.Reader.64-bit","GIMP.GIMP","dotPDN.PaintDotNet","Microsoft.PowerToys",
        "ShareX.ShareX"
    )
    "Web Developer" = @(
        "Microsoft.VisualStudioCode","Git.Git","OpenJS.NodeJS.LTS","Docker.DockerDesktop","Postman.Postman",
        "Mozilla.Firefox","Google.Chrome","GitHub.GitHubDesktop","GitHub.cli","Microsoft.WindowsTerminal",
        "Starship.Starship","ajeetdsouza.zoxide"
    )
    "Python Developer" = @(
        "Microsoft.VisualStudioCode","Git.Git","Python.Python.3.13","Anaconda.Miniconda3","Docker.DockerDesktop",
        "Postman.Postman","JetBrains.PyCharm.Community","Microsoft.WindowsTerminal","DBeaver.DBeaver"
    )
    "Creative Suite" = @(
        "GIMP.GIMP","KDE.Krita","Inkscape.Inkscape","BlenderFoundation.Blender","OBSProject.OBSStudio",
        "HandBrake.HandBrake","Audacity.Audacity","KDE.Kdenlive","Meltytech.Shotcut","ShareX.ShareX",
        "BlackmagicDesign.DaVinciResolve"
    )
    "Gaming PC" = @(
        "Valve.Steam","EpicGames.EpicGamesLauncher","GOG.Galaxy","Discord.Discord","Playnite.Playnite",
        "MoonlightGameStreamingProject.Moonlight","LizardByte.Sunshine","7zip.7zip","Guru3D.Afterburner","TechPowerUp.NVCleanstall"
    )
    "Privacy & Security" = @(
        "Mozilla.Firefox","MullvadVPN.MullvadBrowser","Bitwarden.Bitwarden","ProtonTechnologies.ProtonVPN","LibreWolf.LibreWolf",
        "OpenWhisperSystems.Signal","IDRIX.VeraCrypt","Cryptomator.Cryptomator","henrypp.simplewall","MullvadVPN.MullvadVPN"
    )
    "System Admin" = @(
        "PuTTY.PuTTY","WinSCP.WinSCP","Mobatek.MobaXterm","WiresharkFoundation.Wireshark","Insecure.Nmap",
        "Microsoft.WindowsTerminal","Microsoft.PowerShell","voidtools.Everything","Notepad++.Notepad++","mRemoteNG.mRemoteNG",
        "angryip.ipscan","Microsoft.Sysinternals.ProcessExplorer"
    )
    "Streaming Setup" = @(
        "OBSProject.OBSStudio","Streamlabs.Streamlabs","VB-Audio.Voicemeeter.Banana","VB-Audio.VBVirtualCable","Discord.Discord",
        "ShareX.ShareX","HandBrake.HandBrake","Gyan.FFmpeg","File-New-Project.EarTrumpet"
    )
    "Office & Productivity" = @(
        "TheDocumentFoundation.LibreOffice","Mozilla.Thunderbird","Bitwarden.Bitwarden","Doist.Todoist","Obsidian.Obsidian",
        "7zip.7zip","Adobe.Acrobat.Reader.64-bit","geek.PDF24Creator","Notion.Notion","VideoLAN.VLC"
    )
    "3D Printing Workshop" = @(
        "UltiMaker.Cura","Prusa3D.PrusaSlicer","Bambulab.Bambustudio","SoftFever.OrcaSlicer","FreeCAD.FreeCAD",
        "OpenSCAD.OpenSCAD","BlenderFoundation.Blender"
    )
}
$wingetterRoot = Get-WingetterRootPath
if (![string]::IsNullOrWhiteSpace($wingetterRoot)) {
    $groupsPath = Join-Path $wingetterRoot "catalog\groups.json"
    $externalGroups = ConvertFrom-WingetterGroupsJson -Path $groupsPath
    if ($externalGroups) {
        $Script:BuiltInGroups = $externalGroups
    }
}
