# ============================================================================
# PACKAGE GROUPS SYSTEM
# ============================================================================

$Script:GroupsDir = "$env:APPDATA\Wingetter"
$Script:GroupsFile = "$Script:GroupsDir\groups.json"
if (!(Test-Path $Script:GroupsDir)) { New-Item -ItemType Directory -Path $Script:GroupsDir -Force | Out-Null }

function Get-SavedGroups {
    if (Test-Path $Script:GroupsFile) {
        try { return (Get-Content $Script:GroupsFile -Raw | ConvertFrom-Json) }
        catch { return [PSCustomObject]@{} }
    }
    return [PSCustomObject]@{}
}

function Save-GroupToFile {
    param([string]$Name, [string[]]$PackageIds)
    $groups = Get-SavedGroups
    $ht = @{}
    foreach ($prop in $groups.PSObject.Properties) { $ht[$prop.Name] = @($prop.Value) }
    $ht[$Name] = $PackageIds
    $ht | ConvertTo-Json -Depth 5 | Set-Content -Path $Script:GroupsFile -Encoding UTF8
}

function Remove-GroupFromFile {
    param([string]$Name)
    $groups = Get-SavedGroups
    $ht = @{}
    foreach ($prop in $groups.PSObject.Properties) { if ($prop.Name -ne $Name) { $ht[$prop.Name] = @($prop.Value) } }
    $ht | ConvertTo-Json -Depth 5 | Set-Content -Path $Script:GroupsFile -Encoding UTF8
}

function Export-GroupAsPS1 {
    param([string]$GroupName, [string[]]$PackageIds, [string]$FilePath, [bool]$Silent = $true, [bool]$AcceptAgreements = $true)
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine("<#")
    [void]$sb.AppendLine(".SYNOPSIS")
    [void]$sb.AppendLine("    WinGet Package Group Installer - $GroupName")
    [void]$sb.AppendLine(".DESCRIPTION")
    [void]$sb.AppendLine("    Auto-generated by Wingetter")
    [void]$sb.AppendLine("    Installs $($PackageIds.Count) packages via winget")
    [void]$sb.AppendLine("    Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
    [void]$sb.AppendLine("#>")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine('Write-Host "====================================" -ForegroundColor Cyan')
    [void]$sb.AppendLine("Write-Host `" WinGet Package Group: $GroupName`" -ForegroundColor Cyan")
    [void]$sb.AppendLine("Write-Host `" $($PackageIds.Count) packages to install`" -ForegroundColor Cyan")
    [void]$sb.AppendLine('Write-Host "====================================" -ForegroundColor Cyan')
    [void]$sb.AppendLine('Write-Host ""')
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine('# Check for winget')
    [void]$sb.AppendLine('if (!(Get-Command winget -ErrorAction SilentlyContinue)) {')
    [void]$sb.AppendLine('    Write-Host "ERROR: winget not found. Install it from the Microsoft Store." -ForegroundColor Red')
    [void]$sb.AppendLine('    exit 1')
    [void]$sb.AppendLine('}')
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine('$total = ' + $PackageIds.Count)
    [void]$sb.AppendLine('$current = 0; $ok = 0; $fail = 0; $skip = 0')
    [void]$sb.AppendLine("")

    $flags = ""
    if ($Silent) { $flags += " --silent" }
    if ($AcceptAgreements) { $flags += " --accept-package-agreements --accept-source-agreements" }

    [void]$sb.AppendLine('$packages = @(')
    foreach ($id in $PackageIds) {
        [void]$sb.AppendLine("    `"$id`"")
    }
    [void]$sb.AppendLine(')')
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine('foreach ($pkg in $packages) {')
    [void]$sb.AppendLine('    $current++')
    [void]$sb.AppendLine('    $pct = [math]::Round(($current / $total) * 100)')
    [void]$sb.AppendLine('    Write-Host "[$current/$total] ($pct%) Installing $pkg..." -ForegroundColor Yellow')
    [void]$sb.AppendLine("    `$result = winget install --id `$pkg --exact$flags 2>&1 | Out-String")
    [void]$sb.AppendLine('    if ($LASTEXITCODE -eq 0) {')
    [void]$sb.AppendLine('        Write-Host "  OK" -ForegroundColor Green; $ok++')
    [void]$sb.AppendLine('    } elseif ($result -match "already installed|No available upgrade") {')
    [void]$sb.AppendLine('        Write-Host "  Already installed" -ForegroundColor DarkGray; $skip++')
    [void]$sb.AppendLine('    } else {')
    [void]$sb.AppendLine('        Write-Host "  FAILED" -ForegroundColor Red; $fail++')
    [void]$sb.AppendLine('    }')
    [void]$sb.AppendLine('}')
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine('Write-Host ""')
    [void]$sb.AppendLine('Write-Host "====================================" -ForegroundColor Cyan')
    [void]$sb.AppendLine('Write-Host " Results: $ok installed, $skip already present, $fail failed" -ForegroundColor Cyan')
    [void]$sb.AppendLine('Write-Host "====================================" -ForegroundColor Cyan')
    [void]$sb.AppendLine('Read-Host "Press Enter to exit"')

    $sb.ToString() | Set-Content -Path $FilePath -Encoding UTF8
}

function Export-GroupAsJSON {
    param([string]$GroupName, [string[]]$PackageIds, [string]$FilePath)
    $obj = @{
        Schema     = "Wingetter.Group.v1"
        GroupName  = $GroupName
        Generated  = (Get-Date -Format "yyyy-MM-dd HH:mm:ss")
        Generator  = "Wingetter"
        AppCount   = $PackageIds.Count
        PackageIds = $PackageIds
    }
    $obj | ConvertTo-Json -Depth 5 | Set-Content -Path $FilePath -Encoding UTF8
}

function Export-GroupAsWinGetJSON {
    param([string]$GroupName, [string[]]$PackageIds, [string]$FilePath)

    $wingetVersion = try { (winget --version 2>$null) } catch { $null }
    $packages = @($PackageIds | ForEach-Object {
        [ordered]@{ PackageIdentifier = $_ }
    })

    $obj = [ordered]@{
        '$schema'     = "https://aka.ms/winget-packages.schema.2.0.json"
        CreationDate  = (Get-Date).ToUniversalTime().ToString("o")
        Sources       = @(
            [ordered]@{
                Packages      = $packages
                SourceDetails = [ordered]@{
                    Argument   = "https://cdn.winget.microsoft.com/cache"
                    Identifier = "Microsoft.Winget.Source_8wekyb3d8bbwe"
                    Name       = "winget"
                    Type       = "Microsoft.PreIndexed.Package"
                }
            }
        )
    }
    if ($wingetVersion) { $obj["WinGetVersion"] = [string]$wingetVersion }

    $obj | ConvertTo-Json -Depth 8 | Set-Content -Path $FilePath -Encoding UTF8
}

function Get-JsonPropertyValue {
    param([object]$InputObject, [string]$PropertyName)
    if ($null -eq $InputObject) { return $null }
    $property = $InputObject.PSObject.Properties[$PropertyName]
    if ($property) { return $property.Value }
    return $null
}

function Import-PackageIdsFromJSON {
    param([object]$Content, [string]$FallbackGroupName = "Imported Group")

    $ids = [System.Collections.ArrayList]::new()
    $sourceNames = [System.Collections.ArrayList]::new()
    $warnings = [System.Collections.ArrayList]::new()
    $groupName = $FallbackGroupName
    $format = "Unknown"

    $packageIds = Get-JsonPropertyValue -InputObject $Content -PropertyName "PackageIds"
    $wingetSources = Get-JsonPropertyValue -InputObject $Content -PropertyName "Sources"
    $flatPackages = Get-JsonPropertyValue -InputObject $Content -PropertyName "Packages"

    if ($packageIds) {
        $format = "Wingetter group JSON"
        $name = Get-JsonPropertyValue -InputObject $Content -PropertyName "GroupName"
        if ($name) { $groupName = [string]$name }
        foreach ($id in @($packageIds)) {
            if (![string]::IsNullOrWhiteSpace([string]$id)) { [void]$ids.Add([string]$id) }
        }
    } elseif ($wingetSources) {
        $format = "WinGet import JSON"
        foreach ($source in @($wingetSources)) {
            $sourceDetails = Get-JsonPropertyValue -InputObject $source -PropertyName "SourceDetails"
            $sourceName = Get-JsonPropertyValue -InputObject $sourceDetails -PropertyName "Name"
            if (!$sourceName) { $sourceName = Get-JsonPropertyValue -InputObject $source -PropertyName "Name" }
            if ($sourceName) {
                [void]$sourceNames.Add([string]$sourceName)
            } else {
                [void]$warnings.Add("A WinGet source entry is missing SourceDetails.Name.")
            }

            $sourcePackages = Get-JsonPropertyValue -InputObject $source -PropertyName "Packages"
            foreach ($package in @($sourcePackages)) {
                $id = Get-JsonPropertyValue -InputObject $package -PropertyName "PackageIdentifier"
                if ($id) {
                    [void]$ids.Add([string]$id)
                } else {
                    [void]$warnings.Add("A WinGet package entry is missing PackageIdentifier.")
                }
            }
        }
    } elseif ($flatPackages) {
        $format = "WinGet package list JSON"
        foreach ($package in @($flatPackages)) {
            $id = Get-JsonPropertyValue -InputObject $package -PropertyName "PackageIdentifier"
            if ($id) { [void]$ids.Add([string]$id) }
        }
    } elseif ($Content -is [System.Array]) {
        $format = "Package ID array JSON"
        foreach ($id in @($Content)) {
            if (![string]::IsNullOrWhiteSpace([string]$id)) { [void]$ids.Add([string]$id) }
        }
    } else {
        throw "Unrecognized JSON format"
    }

    $seen = @{}
    $uniqueIds = [System.Collections.ArrayList]::new()
    foreach ($id in $ids) {
        if (!$seen.ContainsKey($id)) {
            $seen[$id] = $true
            [void]$uniqueIds.Add($id)
        }
    }

    [PSCustomObject]@{
        GroupName   = $groupName
        Format      = $format
        PackageIds  = [string[]]$uniqueIds.ToArray([string])
        SourceNames = [string[]]$sourceNames.ToArray([string])
        Warnings    = [string[]]$warnings.ToArray([string])
    }
}

# Pre-built groups
$Script:BuiltInGroups = [ordered]@{
    "Essential PC Setup" = @(
        "Google.Chrome","Mozilla.Firefox","7zip.7zip","VideoLAN.VLC","Notepad++.Notepad++",
        "voidtools.Everything","Adobe.Acrobat.Reader.64-bit","GIMP.GIMP","dotPDN.PaintDotNet","Microsoft.PowerToys",
        "ShareX.ShareX"
    )
    "Web Developer" = @(
        "Microsoft.VisualStudioCode","Git.Git","OpenJS.NodeJS.LTS","Docker.DockerDesktop","Postman.Postman",
        "Mozilla.Firefox","Google.Chrome","GitHub.GitHubDesktop","GitHub.cli","Microsoft.WindowsTerminal",
        "Starship.Starship","ajeetdsouza.zoxide"
    )
    "Python Developer" = @(
        "Microsoft.VisualStudioCode","Git.Git","Python.Python.3.13","Anaconda.Miniconda3","Docker.DockerDesktop",
        "Postman.Postman","JetBrains.PyCharm.Community","Microsoft.WindowsTerminal","DBeaver.DBeaver"
    )
    "Creative Suite" = @(
        "GIMP.GIMP","KDE.Krita","Inkscape.Inkscape","BlenderFoundation.Blender","OBSProject.OBSStudio",
        "HandBrake.HandBrake","Audacity.Audacity","KDE.Kdenlive","Meltytech.Shotcut","ShareX.ShareX",
        "BlackmagicDesign.DaVinciResolve"
    )
    "Gaming PC" = @(
        "Valve.Steam","EpicGames.EpicGamesLauncher","GOG.Galaxy","Discord.Discord","Playnite.Playnite",
        "MoonlightGameStreamingProject.Moonlight","LizardByte.Sunshine","7zip.7zip","Guru3D.Afterburner","TechPowerUp.NVCleanstall"
    )
    "Privacy & Security" = @(
        "Mozilla.Firefox","MullvadVPN.MullvadBrowser","Bitwarden.Bitwarden","ProtonTechnologies.ProtonVPN","LibreWolf.LibreWolf",
        "OpenWhisperSystems.Signal","IDRIX.VeraCrypt","Cryptomator.Cryptomator","henrypp.simplewall","MullvadVPN.MullvadVPN"
    )
    "System Admin" = @(
        "PuTTY.PuTTY","WinSCP.WinSCP","Mobatek.MobaXterm","WiresharkFoundation.Wireshark","Insecure.Nmap",
        "Microsoft.WindowsTerminal","Microsoft.PowerShell","voidtools.Everything","Notepad++.Notepad++","mRemoteNG.mRemoteNG",
        "angryip.ipscan","Microsoft.Sysinternals.ProcessExplorer"
    )
    "Streaming Setup" = @(
        "OBSProject.OBSStudio","Streamlabs.Streamlabs","VB-Audio.Voicemeeter.Banana","VB-Audio.VBVirtualCable","Discord.Discord",
        "ShareX.ShareX","HandBrake.HandBrake","Gyan.FFmpeg","File-New-Project.EarTrumpet"
    )
    "Office & Productivity" = @(
        "TheDocumentFoundation.LibreOffice","Mozilla.Thunderbird","Bitwarden.Bitwarden","Doist.Todoist","Obsidian.Obsidian",
        "7zip.7zip","Adobe.Acrobat.Reader.64-bit","geek.PDF24Creator","Notion.Notion","VideoLAN.VLC"
    )
    "3D Printing Workshop" = @(
        "UltiMaker.Cura","Prusa3D.PrusaSlicer","Bambulab.Bambustudio","SoftFever.OrcaSlicer","FreeCAD.FreeCAD",
        "OpenSCAD.OpenSCAD","BlenderFoundation.Blender"
    )
}
$wingetterRoot = Get-WingetterRootPath
if (![string]::IsNullOrWhiteSpace($wingetterRoot)) {
    $groupsPath = Join-Path $wingetterRoot "catalog\groups.json"
    $externalGroups = ConvertFrom-WingetterGroupsJson -Path $groupsPath
    if ($externalGroups) {
        $Script:BuiltInGroups = $externalGroups
    }
}
